version: "3.8"

services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo
    ports:
      - "8042:80"
    volumes:
      - ./data:/data
    restart: unless-stopped
    stdin_open: true
    tty: true
    working_dir: /data
    entrypoint: ["/bin/bash", "-c", "/data/start-script.sh"]
